version: '3'
services:
  #### MONGO SERVICE ####
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
  ##### MONGO EXPRESS SERVICE ####
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: campfire
      ME_CONFIG_MONGODB_ADMINPASSWORD: campfire_123
      ME_CONFIG_MONGODB_URL: mongodb://campfire:campfire_123@mongo:27017/
    depends_on:
      - mongo
  ##### NEST JS API SERVICE ####
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
      # only will build development stage from our docker file.
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # This is the only change
    env_file:
      - .env
    depends_on:
      - mongo
      - mongo-express
      # Run a command against the development stage of the image
    command: yarn run start
    ports:
      - 3000:3000
networks:
  campfire_network:
    driver: bridge
volumes:
  mongodata:
    driver: local