type PublicNavigationParamList = {
  Welcome: undefined;
  EmailLogin: undefined;
  ReSendEmail: { email: string };
  WelcomeBack: undefined;
  Password: undefined;
  JoinWaitList: undefined;
  AllreadyVerified: { email: string };
  Home: undefined;
  FirstName: undefined;
  Describes: undefined;
  Country: undefined;
  Age: undefined;
  CreateProfile: undefined;
  Adventurous: undefined;
  Adventure: undefined;
  Wishes: undefined;
  Character: undefined;
  UploadPhoto: undefined;
  ForgotPassword: undefined;
};
