export enum OnboardingStep {
  INITIAL = "INITIAL",
  FIRST_NAME = "FIRST_NAME",
  GENDER = "GENDER",
  COUNTRY = "COUNTRY",
  AGE = "AGE",
  CREATE_PROFILE = "CREATE_PROFILE",
  ADVENTURE = "ADVENTURE",
  TOP_WISHES = "TOP_WISHES",
  NEXT_ADVENTURE = "NEXT_ADVENTURE",
  CHARACTER = "CHARACTER",
  PHOTOS = "PHOTOS",
  COMPLETED = "COMPLETED",
}
